# christmas (final code) written by virgilholmes
def christmasMusic():
    music.set_volume(2000)
    music.set_tempo(108)
    music.play(music.tone_playable(Note.G, music.beat(BeatFraction.WHOLE)), music.PlaybackMode.UNTIL_DONE)
    music.rest(music.beat(BeatFraction.HALF))
    music.play(music.tone_playable(Note.G, music.beat(BeatFraction.WHOLE)), music.PlaybackMode.UNTIL_DONE)
    music.play(music.tone_playable(Note.F, music.beat(BeatFraction.HALF)), music.PlaybackMode.UNTIL_DONE)
    music.rest(music.beat(BeatFraction.HALF))
    music.play(music.tone_playable(Note.C, music.beat(BeatFraction.HALF)), music.PlaybackMode.UNTIL_DONE)
    music.play(music.tone_playable(Note.G, music.beat(BeatFraction.HALF)), music.PlaybackMode.UNTIL_DONE)
    music.play(music.tone_playable(Note.G, music.beat(BeatFraction.HALF)), music.PlaybackMode.UNTIL_DONE)
    music.play(music.tone_playable(Note.A, music.beat(BeatFraction.HALF)), music.PlaybackMode.UNTIL_DONE)
    music.play(music.tone_playable(Note.F, music.beat(BeatFraction.WHOLE)), music.PlaybackMode.UNTIL_DONE)
    music.rest(music.beat(BeatFraction.HALF))
    music.play(music.tone_playable(Note.D, music.beat(BeatFraction.HALF)), music.PlaybackMode.UNTIL_DONE)
    music.play(music.tone_playable(Note.D, music.beat(BeatFraction.HALF)), music.PlaybackMode.UNTIL_DONE)
    music.play(music.tone_playable(Note.G, music.beat(BeatFraction.HALF)), music.PlaybackMode.UNTIL_DONE)
    music.play(music.tone_playable(Note.G, music.beat(BeatFraction.HALF)), music.PlaybackMode.UNTIL_DONE)
    music.play(music.tone_playable(Note.A, music.beat(BeatFraction.WHOLE)), music.PlaybackMode.UNTIL_DONE)
    music.play(music.tone_playable(Note.F, music.beat(BeatFraction.WHOLE)), music.PlaybackMode.UNTIL_DONE)
    music.rest(music.beat(BeatFraction.HALF))
    music.play(music.tone_playable(Note.D, music.beat(BeatFraction.HALF)), music.PlaybackMode.UNTIL_DONE)
    music.play(music.tone_playable(Note.E, music.beat(BeatFraction.HALF)), music.PlaybackMode.UNTIL_DONE)
    music.play(music.tone_playable(Note.F, music.beat(BeatFraction.HALF)), music.PlaybackMode.UNTIL_DONE)
    music.play(music.tone_playable(Note.E, music.beat(BeatFraction.HALF)), music.PlaybackMode.UNTIL_DONE)
    music.play(music.tone_playable(Note.D, music.beat(BeatFraction.DOUBLE)), music.PlaybackMode.UNTIL_DONE)
    music.rest(music.beat(BeatFraction.HALF))

    music.play(music.tone_playable(Note.A, music.beat(BeatFraction.WHOLE)), music.PlaybackMode.UNTIL_DONE)
    music.rest(music.beat(BeatFraction.HALF))
    music.play(music.tone_playable(Note.G, music.beat(BeatFraction.WHOLE)), music.PlaybackMode.UNTIL_DONE)
    music.rest(music.beat(BeatFraction.HALF))
    music.play(music.tone_playable(Note.D, music.beat(BeatFraction.HALF)), music.PlaybackMode.UNTIL_DONE)
    music.play(music.tone_playable(Note.A, music.beat(BeatFraction.HALF)), music.PlaybackMode.UNTIL_DONE)
    music.play(music.tone_playable(Note.BB, music.beat(BeatFraction.HALF)), music.PlaybackMode.UNTIL_DONE)
    music.play(music.tone_playable(Note.A, music.beat(BeatFraction.HALF)), music.PlaybackMode.UNTIL_DONE)
    music.play(music.tone_playable(Note.G, music.beat(BeatFraction.WHOLE)), music.PlaybackMode.UNTIL_DONE)
    music.rest(music.beat(BeatFraction.HALF))

    music.play(music.tone_playable(Note.F, music.beat(BeatFraction.HALF)), music.PlaybackMode.UNTIL_DONE)
    music.play(music.tone_playable(Note.E, music.beat(BeatFraction.HALF)), music.PlaybackMode.UNTIL_DONE)
    music.play(music.tone_playable(Note.F, music.beat(BeatFraction.HALF)), music.PlaybackMode.UNTIL_DONE)
    music.play(music.tone_playable(Note.E, music.beat(BeatFraction.HALF)), music.PlaybackMode.UNTIL_DONE)
    music.play(music.tone_playable(Note.E, music.beat(BeatFraction.WHOLE)), music.PlaybackMode.UNTIL_DONE)
    music.play(music.tone_playable(Note.F, music.beat(BeatFraction.WHOLE)), music.PlaybackMode.UNTIL_DONE)
    music.play(music.tone_playable(Note.E, music.beat(BeatFraction.WHOLE)), music.PlaybackMode.UNTIL_DONE)
    music.play(music.tone_playable(Note.C, music.beat(BeatFraction.DOUBLE)), music.PlaybackMode.UNTIL_DONE)

def on_forever():
    pins.analog_write_pin(AnalogPin.P0, 1023)
    pins.analog_write_pin(AnalogPin.P8, 0)
    basic.pause(500)
    pins.analog_write_pin(AnalogPin.P0, 0)
    pins.analog_write_pin(AnalogPin.P1, 1023)
    basic.pause(500)
    pins.analog_write_pin(AnalogPin.P2, 1023)
    pins.analog_write_pin(AnalogPin.P1, 0)
    basic.pause(500)
    pins.analog_write_pin(AnalogPin.P8, 1023)
    pins.analog_write_pin(AnalogPin.P2, 0)
    basic.pause(500)

basic.forever(on_forever)
def on_button_pressed_a():
    while True:
        christmasMusic()
def on_button_pressed_b():
    control.reset()
input.on_button_pressed(Button.A, on_button_pressed_a)
input.on_button_pressed(Button.B, on_button_pressed_b)

basic.pause(1000)
